### ISSUE TITLE
after adding a point on a graph is it possible to move that points instead of drag functionality ?

### ISSUE THREAD

**Issue by Wijikhan** [ellsworthrw/DiamondCharts#2]
for now in functional graph we have drag that let us know about the details of points but i want to add the points on graph and then let these points to move on the graph when ever i drags the point on graph.
Thanks in advance for help.

**Comment by ellsworthrw** [comment]
As mentioned in your last question: You need to implement a class that provides the data points i.e. it implements `ChartData`. In your app you provide the data in whatever way fits your needs. Then follow the sample app for how to provide touch support to display the details of a data point.
